# Generated by Django 3.2.7 on 2021-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
