# Generated by Django 3.2.7 on 2021-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='usability',
            field=models.FloatField(default=0),
        ),
    ]
