# Generated by Django 3.2.7 on 2021-09-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210922_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='content',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='design',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='usability',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('design', models.FloatField(default=0)),
                ('usability', models.FloatField(default=0)),
                ('content', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
    ]
