# Generated by Django 3.2.7 on 2021-09-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210923_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='usability',
            new_name='userbility',
        ),
    ]
