# Generated by Django 3.2.7 on 2021-09-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_usability_review_userbility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userbility',
            new_name='usability',
        ),
    ]
